export const TIMERS_FETCH_REQUEST = 'app/TIMERS_FETCH_REQUEST';
export const TIMERS_FETCH_SUCCESS = 'app/TIMERS_FETCH_SUCCESS';
export const TIMERS_FETCH_FAILURE = 'app/TIMERS_FETCH_FAILURE';

export const SET_EDIT_TIMER = 'control/SET_EDIT_TIMER';

export const SET_TIMERS = 'app/SET_TIMERS';

export const TIMER_ADD_REQUEST = 'app/TIMER_ADD_REQUEST';
export const TIMER_ADD_SUCCESS = 'app/TIMER_ADD_SUCCESS';
export const TIMER_ADD_FAILED = 'app/TIMER_ADD_FAILED';

export const TIMER_UPDATE_REQUEST = 'app/TIMER_UPDATE_REQUEST';
export const TIMER_UPDATE_SUCCESS = 'app/TIMER_UPDATE_SUCCESS';
export const TIMER_UPDATE_FAILED = 'app/TIMER_UPDATE_FAILED';

export const REMOVE_TIMER_REQUEST = 'app/REMOVE_TIMER_REQUEST';
export const REMOVE_TIMER_SUCCESS = 'app/REMOVE_TIMER_SUCCESS';
export const REMOVE_TIMER_FAILURE = 'app/REMOVE_TIMER_FAILURE';

export const TIMER_START = 'app/TIMER_START';
export const TIMER_START_SUCCESS = 'app/TIMER_START_SUCCESS';
export const TIMER_START_FAILED = 'app/TIMER_START_FAILED';

export const CURRENT_TIMER_SET = 'app/CURRENT_TIMER_SET';
